spring:
  profiles:
    active: dev

logging:
  level:
    root: info
    com.zl: debug

server:
  port: 7777

mybatis:
  mapper-locations: classpath:mapper/*.xml

wechat:
  appid: ${wechat.appid}
  secretid: ${wechat.secretid}
